server:
  port: 8080
  
spring.datasource.schema: public
spring.jpa.show-sql: true
spring.datasource.url: jdbc:postgresql://localhost/postgres
spring.datasource.username: postgres
spring.datasource.password: postgres@ragesh
spring.jpa.hibernate.ddl-auto: create-drop